// Registry of code-defined provisioning config modules.
// Add a module: create its file under the matching folder, then add one
// import + one array entry below. Initially generated by
// scripts/generateModules.ts; hand-edited thereafter.
import type {
  AppProfileModule,
  ConfigProfileModule,
  DeploymentModule,
  GroupedProfile,
  ProviderProfileModule,
  ResourceProfileModule,
} from "./types.js";

import pp_aws_lab from "./provider-profiles/aws-lab.js";
import pp_proxmox_home from "./provider-profiles/proxmox-home.js";
import rp_aws_egress_route from "./resource-profiles/aws-egress-route.js";
import rp_aws_network from "./resource-profiles/aws-network.js";
import rp_aws_panorama from "./resource-profiles/aws-panorama.js";
import rp_aws_panw_vmseries from "./resource-profiles/aws-panw-vmseries.js";
import rp_aws_s3_bucket from "./resource-profiles/aws-s3-bucket.js";
import rp_aws_ubuntu_server from "./resource-profiles/aws-ubuntu-server.js";
import rp_aws_windows_endpoint from "./resource-profiles/aws-windows-endpoint.js";
import dep_aws_enterprise_firewall from "./deployments/aws-enterprise-firewall.js";
import dep_aws_gp_lab_trusted_users from "./deployments/aws-gp-lab-trusted-users.js";
import dep_aws_panorama_lan from "./deployments/aws-panorama-lan.js";
import dep_aws_s3_bootstrap from "./deployments/aws-s3-bootstrap.js";
import dep_aws_single_firewall from "./deployments/aws-single-firewall.js";
import dep_aws_ubuntu_behind_firewall from "./deployments/aws-ubuntu-behind-firewall.js";
import dep_aws_ubuntu_koi_endpoint from "./deployments/aws-ubuntu-koi-endpoint.js";
import dep_aws_ubuntu_server from "./deployments/aws-ubuntu-server.js";
import dep_aws_windows_endpoint from "./deployments/aws-windows-endpoint.js";
import dep_proxmox_fw_lab from "./deployments/proxmox-fw-lab.js";
import app_linux_codex_claude from "./app-profiles/linux/codex-claude.js";
import app_windows_cortex_xdr from "./app-profiles/windows/cortex-xdr.js";
import app_windows_developer from "./app-profiles/windows/developer.js";
import cfg_panw_vmseries_enterprise_rule_stack from "./config-profiles/panw-vmseries/enterprise-rule-stack.js";
import cfg_panw_vmseries_internet_egress from "./config-profiles/panw-vmseries/internet-egress.js";

export const providerProfiles: ProviderProfileModule[] = [
  pp_aws_lab,
  pp_proxmox_home,
];

export const resourceProfiles: ResourceProfileModule[] = [
  rp_aws_egress_route,
  rp_aws_network,
  rp_aws_panorama,
  rp_aws_panw_vmseries,
  rp_aws_s3_bucket,
  rp_aws_ubuntu_server,
  rp_aws_windows_endpoint,
];

export const deployments: DeploymentModule[] = [
  dep_aws_enterprise_firewall,
  dep_aws_gp_lab_trusted_users,
  dep_aws_panorama_lan,
  dep_aws_s3_bootstrap,
  dep_aws_single_firewall,
  dep_aws_ubuntu_behind_firewall,
  dep_aws_ubuntu_koi_endpoint,
  dep_aws_ubuntu_server,
  dep_aws_windows_endpoint,
  dep_proxmox_fw_lab,
];

export const appProfiles: GroupedProfile<AppProfileModule>[] = [
  { group: "linux", profile: app_linux_codex_claude },
  { group: "windows", profile: app_windows_cortex_xdr },
  { group: "windows", profile: app_windows_developer },
];

export const configProfiles: GroupedProfile<ConfigProfileModule>[] = [
  { group: "panw-vmseries", profile: cfg_panw_vmseries_enterprise_rule_stack },
  { group: "panw-vmseries", profile: cfg_panw_vmseries_internet_egress },
];

export function findAppProfile(group: string, name: string): AppProfileModule | null {
  return appProfiles.find((e) => e.group === group && e.profile.name === name)?.profile ?? null;
}

export function findConfigProfile(group: string, name: string): ConfigProfileModule | null {
  return configProfiles.find((e) => e.group === group && e.profile.name === name)?.profile ?? null;
}
