#!/usr/bin/env bash
# Interactive setup — walks a new operator through the required environment
# variables and writes a .env file at the repo root. Re-run any time; it
# prompts before overwriting an existing .env.
#
# All values are also settable directly via env vars (e.g. for CI / Docker /
# K8s deploys that skip this script). See .env.example for the full list.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
TODOIST_ENV_FILE="$ROOT/todoist/.env"

bold() { printf '\033[1m%s\033[0m' "$1"; }
dim()  { printf '\033[2m%s\033[0m' "$1"; }
ok()   { printf '\033[32m%s\033[0m\n' "$1"; }
warn() { printf '\033[33m%s\033[0m\n' "$1"; }
err()  { printf '\033[31m%s\033[0m\n' "$1" >&2; }

prompt() {
  # $1 question  $2 default  → echoes the answer
  local q="$1" def="${2:-}" reply
  if [[ -n "$def" ]]; then
    read -r -p "$(bold "$q") [$(dim "$def")]: " reply || true
    echo "${reply:-$def}"
  else
    read -r -p "$(bold "$q"): " reply || true
    echo "$reply"
  fi
}

prompt_secret() {
  local q="$1" reply
  read -r -s -p "$(bold "$q") (input hidden, leave blank to skip): " reply || true
  echo
  echo "$reply"
}

random_password() {
  # 32 hex chars. Using openssl avoids the `tr < /dev/urandom | head -c N`
  # pattern, which dies under `set -euo pipefail` because head closes the pipe
  # and tr exits 141 (SIGPIPE), aborting the script silently.
  openssl rand -hex 16
}

if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE"
  reply=$(prompt "Overwrite? (y/N)" "N")
  case "$reply" in
    y|Y|yes|YES) ;;
    *) echo "Aborted. Edit $ENV_FILE directly to change settings."; exit 0 ;;
  esac
fi

cat <<EOF

╔══════════════════════════════════════════════════════════╗
║   CRAM — Customer Relationship Agentic Manager           ║
║   Setup                                                  ║
╚══════════════════════════════════════════════════════════╝

This will write .env at the repo root. You can change anything later by
editing that file directly or re-running this script.

Press Enter to accept the default shown in brackets.

EOF

bold "Identity"; echo
echo "These shape the agent's system prompt and the workflow guidance the MCP server delivers to LLMs."
VENDOR_NAME=$(prompt "Your company / vendor name" "Acme Corp")
USER_ROLE=$(prompt "Your role" "Sales Engineer")
echo

bold "Postgres"; echo
echo "The bundled Docker compose stack runs a local Postgres. Pick a strong password; it never leaves this machine."
POSTGRES_USER=$(prompt "Postgres user" "crm")
POSTGRES_DB=$(prompt "Postgres database name" "crm")
default_pw=$(random_password)
POSTGRES_PASSWORD=$(prompt "Postgres password" "$default_pw")
echo

bold "Todoist (optional)"; echo
echo "Todoist is the bundled task manager. Answer N to skip the integration entirely — no HTTP routes, no MCP tools, no agent guidance about Todoist will be loaded."
use_todoist=$(prompt "Do you use Todoist? (y/N)" "N")
case "$use_todoist" in
  y|Y|yes|YES)
    TODOIST_ENABLED=true
    TODOIST_API_TOKEN=$(prompt_secret "Todoist API token")
    TODOIST_DEFAULT_PROJECT=$(prompt "Todoist default project for new tasks" "Inbox")
    TODOIST_DEFAULT_SECTION=$(prompt "Todoist default section (leave blank for project root)" "")
    ;;
  *)
    TODOIST_ENABLED=false
    TODOIST_API_TOKEN=""
    TODOIST_DEFAULT_PROJECT=""
    TODOIST_DEFAULT_SECTION=""
    ;;
esac
echo

# Write .env at repo root
{
  cat <<EOF
# CRAM — generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run scripts/setup.sh to regenerate, or edit by hand.

# Identity
VENDOR_NAME="$VENDOR_NAME"
USER_ROLE="$USER_ROLE"

# Postgres
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=$POSTGRES_DB
DATABASE_SSL=false

# Anthropic API key — fill in to use Claude as the agent provider. Leave blank
# to use a local LLM (Ollama / LM Studio / llama.cpp / vLLM) configured from
# the GUI Agent page. Provider and model are picked per-request in the GUI.
ANTHROPIC_API_KEY=

# Todoist
EOF
  # When disabled, write the explicit flag. When enabled, omit the flag (default
  # is true at runtime) and write the token + defaults so docker-compose can
  # interpolate them into the container env.
  if [[ "$TODOIST_ENABLED" == "false" ]]; then
    echo "TODOIST_ENABLED=false"
  else
    echo "TODOIST_API_TOKEN=$TODOIST_API_TOKEN"
    echo "TODOIST_DEFAULT_PROJECT=\"$TODOIST_DEFAULT_PROJECT\""
    echo "TODOIST_DEFAULT_SECTION=\"$TODOIST_DEFAULT_SECTION\""
  fi
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
ok "Wrote $ENV_FILE"

# Pre-create the host paths that docker-compose bind-mounts as files. If these
# don't exist on the host before `docker compose up`, Docker creates empty
# directories at the mount points and the outreach module crashes trying to
# read them as JSON files.
mkdir -p "$ROOT/backups" "$ROOT/outreach"
[[ -e "$ROOT/outreach/cookies.json"    ]] || echo '[]' > "$ROOT/outreach/cookies.json"
[[ -e "$ROOT/outreach/.ratelimit.json" ]] || echo '{}' > "$ROOT/outreach/.ratelimit.json"

# Write todoist/.env if the user provided a token (the todoist module reads its
# token from its own .env, not the root one)
if [[ -n "$TODOIST_API_TOKEN" ]]; then
  mkdir -p "$ROOT/todoist"
  cat > "$TODOIST_ENV_FILE" <<EOF
TODOIST_API_TOKEN=$TODOIST_API_TOKEN
EOF
  chmod 600 "$TODOIST_ENV_FILE"
  ok "Wrote $TODOIST_ENV_FILE"
fi

cat <<EOF

$(bold "Next steps:")

  1. Start the stack:
       docker compose --profile prod up -d --build

  2. Open the GUI:
       http://localhost:3200

  3. (Optional) Authenticate LinkedIn for outreach enrichment. Needs Node.js 20+
     on the host, run from a machine with a desktop browser:
       cd outreach && npm install && node src/index.js login
     If your CRAM host is headless, run this on your laptop and copy
     outreach/cookies.json over to the same path on the host.

  4. To update later (pull latest code and restart with a fresh build):
       ./scripts/restart-prod.sh

EOF
